# Test
name: YAMLlint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint and Annotate
        uses: staffbase/yamllint-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          ## The target path is processed recursively
#          target-path: <relative-folder-path>
#          ## The action name is only necessary if the current action name changed
#          action-name: <name-of-the-action>